### ISSUE TITLE
No module named 'torchseq.eval.recipes.opagg.hiro_pre'

### ISSUE THREAD

**Issue by eranfain** [tomhosking/hiro#1]
Hello,

When I try to run the following line as mentioned in the README:
`torchseq-eval --recipe opagg.hiro_pre --model ./models/20240130_183901_d671_space --test`

I get:
`ModuleNotFoundError: No module named 'torchseq.eval.recipes.opagg.hiro_pre'`

When I check the files in torchseq.eval.recipes.opagg I don't find hiro_pre file there (only hero_pre). 
Can you please assist me resolving this issue?

**Comment by tomhosking** [comment]
Sorry about that - you can run `torchseq-eval --recipe opagg.hero_pre --model ./models/20240130_183901_d671_space --test` and it should work OK.

In case you're just trying to get the outputs for Mistral/Llama 7B, these are all available in the repo [here](https://github.com/tomhosking/hiro/tree/main/output/space).

**Comment by eranfain** [comment]
That solved the issue. Thanks!
